apiVersion: v1
kind: Namespace
metadata:
  name: app-test-1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-test-1
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1
  namespace: app-test-1
  labels:
    app: app-test-1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-test-1
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-test-1-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-redirect-from: http://
    nginx.ingress.kubernetes.io/proxy-redirect-to: https://
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  rules:
  - host: gre4ka.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-test-1
            port:
              number: 80
