apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: nginx-cert
  secretName: coffee-secret-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
  - gre4ka.org
  issuerRef:
    name: nginx-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
