name: CI Pipeline

on:
  push:
    branches:
      - ci-cd
jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/app
          tags: |
            type=sha
            latest
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update ArgoCD manifest
        run: |
          ls -l
          cd kubernetes/manifest/app-test-1
          ls -l
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' | grep 'sha-')
          echo "Extracted IMAGE_TAG: ${IMAGE_TAG}"
          sed -i "s|image: da1ly/app:.*|image: ${IMAGE_TAG}|" app-test-1.yaml

      - name: Display ArgoCD manifest after update
        run: cat kubernetes/manifest/app-test-1/app-test-1.yaml
  
      - name: Commit and push ArgoCD manifest update
        run: |
          cd kubernetes/manifest/app-test-1
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add app-test-1.yaml
          git commit -m "Update ArgoCD manifest with new Docker image tag"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Gre4kas/project-kubernetes-learning-.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
